#!./venv/bin/python
import sys
import os
import subprocess

# include ./scripts in path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), 'scripts')))

from format_gcc_output import format_gcc_output

# clear terminal screen
subprocess.run(['clear'])

command = ['make', 'devf']
format_gcc_output (command)

