#!/bin/bash

gcc -g -Wall -Wextra $(ncursesw5-config --cflags) \
\
    ../src/choose_layout.c\
    ../src/display_lines.c\
    ../src/execute_until.c\
    ../src/insert_output_marker.c\
    ../src/parse_config_file.c\
    ../src/parse_debugger_output.c\
    ../src/plugins.c\
    ../src/pulse_header_title_color.c\
    ../src/render_layout.c\
    ../src/run_custom_command.c\
    ../src/run_plugin.c\
    ../src/select_window.c\
    ../src/send_debugger_command.c\
    ../src/start_debugger.c\
    ../src/utilities.c\
\
    ../src/update_window_data/_no_buff_data.c\
    ../src/update_window_data/_update_window_data.c\
    ../src/update_window_data/get_assembly_data.c\
    ../src/update_window_data/get_breakpoint_data.c\
    ../src/update_window_data/get_debugger_output.c\
    ../src/update_window_data/get_local_vars.c\
    ../src/update_window_data/get_program_output.c\
    ../src/update_window_data/get_register_data.c\
    ../src/update_window_data/get_source_path_line_memory.c\
    ../src/update_window_data/get_watchpoint_data.c\
\
    ../src/get_popup_window_input/_get_popup_window_input.c\
    ../src/get_popup_window_input/popup_breakpoints.c\
    ../src/get_popup_window_input/popup_watchpoints.c\
\
    $1\
\
    $(ncursesw5-config --libs) && \
\
./a.out ../misc/gcd.py
