#!/bin/bash

# Run tests on source and/or header file in ../src
#
# Usage:
#
#   $ ./run file_test.c
#

# get test file name
test="$1"

# check if empty string
if [[ -z "$test" ]]; then
    echo "Usage:"
    echo "    $ ./run file_test.c"
    exit 1
fi

# strip file name  ( <name>_test.c )
name="${test%%_test.c}"

# if source file found
if [ -e "../src/$name.c" ]; then

    # build
    echo "Building with source file"
    printf "    gcc -g -o ./test.out $test ../src/$name.c -lncurses ...\n"
    gcc -g -o ./test.out $test ../src/$name.c -lncurses
    build_status=$?

# if only a header file
elif [ -e "../src/$name.h" ]; then

    # build
    echo "No source file found."
    echo "Building with header file only"
    printf "    gcc -g -o ./test.out $test -lncurses ...\n"
    gcc -g -o ./test.out $test -lncurses
    build_status=$?

# if no matching files found, exit
else
    printf "No header found\n\n"
    printf "Make sure the test file name matches its respective\n"
    printf "source and/or header file\n\n"
    printf "    main.c  ->  main_test.c\n\n"
    exit
fi

# if build successful, run
if [ $build_status -eq 0 ]; then
    printf "Running...\n"
    printf "    ./test.out \n"
    printf "___________\n\n"
    ./test.out
    echo "$?"
fi
