#!/bin/bash

#
# Run Tmux debugging session
# ---------
#
# $ make debug
#
# Set breakpoint(s), etc. then 'continue' execution
# 'q' to close session, save breakpoints
#


tmux splitw -h -p 50 "gdbserver :12347 ./termvu_dev -d gdb ./misc/hello 0"
tmux selectp -t 0
gdb --tui --quiet -x .gdbtarget

