#!/bin/sh

#
# Start termfu_dev with gdbserver  (GDB)
#
# Usage:
#
#   $ make server
#   Run `make target` in a different terminal to target this server with termfu
#

CONFIG="scripts/.termfu_server_gdb"
DATA="${CONFIG}_data"

gdbserver :12347 ./termfu_dev -c $CONFIG -d $DATA 0

