#!/bin/sh

#
# Start termfu_dev with gdbserver  (PDB)
#
# Usage:
#
#   $ make server
#   - Creates PID file /tmp/termfu.pid
#   - Run `make conn_proc_<debugger>` in a different terminal to target this process
#

CONFIG="scripts/.termfu_proc_pdb"
DATA="${CONFIG}_data"

./termfu_dev -c $CONFIG -p $DATA -d

