#!/bin/sh

#
# Start termfu_dev with gdbserver  (GDB)
#
# Usage:
#
#   $ make proc_gdb
#   - Run `make conn_proc_<debugger>` in a different terminal to target this process
#   - Creates PID file /tmp/termfu.pid
#

CONFIG="scripts/.termfu_proc_gdb"
DATA="${CONFIG}_data"

./termfu_dev -c $CONFIG -p $DATA -d

