#!/usr/bin/python

from colors import *

T = BOLD_CYAN
M = BOLD_GREEN
S = BOLD_YELLOW
R = RESET

make_commands = f'''

{M}make           {R}- Build production binary

{M}make dev       {R}- Build development binary

{M}make devf      {R}- Build development binary (formatted errors)

{M}make plugins   {R}- Print plugin indexes and codes

{M}make todo      {R}- Print source code tags, e.g. TODO, FIXME

{M}make build_gdb {R}- Build sample binaries for {M}run_dev{R} below

{M}make run_dev   {R}- Run termfu_dev with sample binary or script
               {R}- Adjust {S}configs/.termfu_run_dev{R} as needed

{M}make debug     {R}- Start {M}termfu{R} to debug {M}termfu_dev{R}
               {R}- Requires {M}termfu{R} to be in your {M}PATH{R}
               {R}- See {M}Developer notes{R} in {S}README.md{R} for more details
               {R}- Adjust {S}configs/.termfu_debugger{R} and {S}configs/.termfu_debugged{R} as needed

'''

print (make_commands)

