#!/bin/sh

#
# Output all source code tags recursively in CWD
#
# Usage:
#   $ make todo
#

CWD="src/"

echo ""

grep -rn \
\
    -e "NOTE: " \
    -e "PERF: " \
    -e "TODO: " \
    -e "HACK: " \
    -e "XXX: " \
    -e "FIXME: " \
    -e "BUG: " \
    -e "TEST: " \
\
    $CWD 2>/dev/null --color=auto | \
\
    sed \
    -e "s/^.[^:]*\?/\x1b[1;36m&\x1b[0m/g" \
    -e "s/NOTE/\x1b[0;33m&\x1b[0m/g" \
    -e "s/PERF/\x1b[0;33m&\x1b[0m/g" \
    -e "s/TODO/\x1b[2;32m&\x1b[0m/g" \
    -e "s/HACK/\x1b[0;34m&\x1b[0m/g" \
    -e "s/XXX/\x1b[0;35m&\x1b[0m/g" \
    -e "s/FIXME/\x1b[0;31m&\x1b[0m/g" \
    -e "s/BUG/\x1b[0;91m&\x1b[0m/g" \
    -e "s/TEST/\x1b[0;91m&\x1b[0m/g" | \
\
    awk -F: '{ printf "%-45s %-s\n", $1 ":" $2 ":", substr($0, index($0, "//")) }'

echo ""

