#!/bin/bash

script="$1"

# check if empty string
if [[ -z "$script" ]]; then
    echo "Usage:  ./run script.c"
    exit 1
fi

# strip source file name
src_name="${script%.c}"

gcc -g -Wall -o $src_name $1 -lncurses

./$src_name
