#!/bin/sh

#
# Run tmux GDB TUI debugging session
# ---------
# Ncurses programs have a problem receiving user input when run in a different terminal via GDB's tty command.
# This script solves that issue at the expense of having to quit and rerun it in order to restart the program.
#
# Usage: 
#
#   - Uses the `termfu_dev` build created by `make dev` or `make devf`
#
#   $ make debug
#
#   - In GDB, set (b)reakpoint then (c)ontinue execution
#
#   - Switch to program's tmux pane on right to send key commands
#       - Ctrl+b then right/left arrow
#
#   - In GDB, (q)uit
#

CONFIG="misc/.termfu_tui_pdb"
DATA="${CONFIG}_data"

if [ -z $TMUX ]; then
    tmux
fi

tmux splitw -h -p 50 "gdbserver :12347 ./termfu_dev -c $CONFIG -d $DATA 0"
tmux selectp -t 0
gdb --tui --quiet -x misc/.gdb_tui_target

