#!/bin/sh

#
# Run tmux GDB TUI debugging session on termfu_dev debugging with GDB
# ---------
# Ncurses programs seem to have a problem receiving user input when run in a different terminal via GDB's tty command.
# This script solves that issue at the expense of having to quit and rerun the session.
#
# Usage: 
#
#   - Uses the `termfu_dev` build created by `make dev` or `make devf`
#   $ make tui_gdb
#   - In GDB, set (b)reakpoint then (c)ontinue execution
#   - Switch to program's tmux pane on right to send key commands
#       - Ctrl+b then right/left arrow
#   - In GDB, (q)uit
#
#   - Tip: create a terminal screen refresh shortcut for Ncurses errors
#

CONFIG="scripts/.termfu_tui_gdb"
DATA="${CONFIG}_data"

if [ -z $TMUX ]; then
    tmux
fi

tmux splitw -h -p 50 "gdbserver :12347 ./termfu_dev -c $CONFIG -d $DATA 0"
tmux selectp -t 0
gdb --tui --quiet -x scripts/.gdb_target

